name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Build wheels
        run: pip wheel . --wheel-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}
          path: wheelhouse/
          retention-days: 1  # Optional: Specify the number of days to retain the artifact
          if-no-files-found: error

  test_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Download wheels for linux
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-ubuntu-latest-${{ matrix.python-version }}
          path: wheelhouse/ubuntu-latest/${{ matrix.python-version }}

      - name: Download wheels for windows
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-windows-latest-${{ matrix.python-version }}
          path: wheelhouse/windows-latest/${{ matrix.python-version }}

      - name: Download wheels for macos
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-macos-latest-${{ matrix.python-version }}
          path: wheelhouse/macos-latest/${{ matrix.python-version }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          pip install pytest
          pip install wheelhouse/*/*/*.whl || true  # Allow failing if some wheels are not compatible
          pip install MarkupSafe  # Ensure MarkupSafe is installed from PyPI

      - name: Run tests
        run: pytest

  publish_wheels:
    runs-on: ubuntu-latest
    needs: test_wheels
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download wheels for linux
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-ubuntu-latest-3.10
          path: wheelhouse/ubuntu-latest/3.10

      - name: Download wheels for windows
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-windows-latest-3.10
          path: wheelhouse/windows-latest/3.10

      - name: Download wheels for macos
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-macos-latest-3.10
          path: wheelhouse/macos-latest/3.10

      - name: Download wheels for linux
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-ubuntu-latest-3.11
          path: wheelhouse/ubuntu-latest/3.11

      - name: Download wheels for windows
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-windows-latest-3.11
          path: wheelhouse/windows-latest/3.11

      - name: Download wheels for macos
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse-macos-latest-3.11
          path: wheelhouse/macos-latest/3.11

      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
